举报类型:
  - 言语违规
  - 使用外挂软件
  - 恶意利用bug漏洞
  - 私下RMB交易
#可以添加嗷！
处理方式:
  - "封号|模板1"
  - "踢出玩家"
#目前仅支持 "踢出玩家" 或 "封号|xx"的格式
#添加处理方式后一定要在dealMethod.yml内添加相应部分！
数据库:
  是否启用: false
  ip: "192.168.1.1"
  端口: 19132
  名称: "test"
  用户名: "test"
  密码: "test"